INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (1, ''제목이요1'', ''내용이요1'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (2, ''제목이요2'', ''내용이요2'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (3, ''제목이요3'', ''내용이요3'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (4, ''제목이요4'', ''내용이요4'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (5, ''제목이요5'', ''내용이요5'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (6, ''제목이요6'', ''내용이요6'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (7, ''제목이요7'', ''내용이요7'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (8, ''제목이요8'', ''내용이요8'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (9, ''제목이요9'', ''내용이요9'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (10, ''제목이요10'', ''내용이요10'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (11, ''제목이요11'', ''내용이요11'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (12, ''제목이요12'', ''내용이요12'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (13, ''제목이요13'', ''내용이요13'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (14, ''제목이요14'', ''내용이요14'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (15, ''제목이요15'', ''내용이요15'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (16, ''제목이요16'', ''내용이요16'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (17, ''제목이요17'', ''내용이요17'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (18, ''제목이요18'', ''내용이요18'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (19, ''제목이요19'', ''내용이요19'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (20, ''제목이요20'', ''내용이요20'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (21, ''제목이요21'', ''내용이요21'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (22, ''제목이요22'', ''내용이요22'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (23, ''제목이요23'', ''내용이요23'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (24, ''제목이요24'', ''내용이요24'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (25, ''제목이요25'', ''내용이요25'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (26, ''제목이요26'', ''내용이요26'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (27, ''제목이요27'', ''내용이요27'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (28, ''제목이요28'', ''내용이요28'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (29, ''제목이요29'', ''내용이요29'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (30, ''제목이요30'', ''내용이요30'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (31, ''제목이요31'', ''내용이요31'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (32, ''제목이요32'', ''내용이요32'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (33, ''제목이요33'', ''내용이요33'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (34, ''제목이요34'', ''내용이요34'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (35, ''제목이요35'', ''내용이요35'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (36, ''제목이요36'', ''내용이요36'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (37, ''제목이요37'', ''내용이요37'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (38, ''제목이요38'', ''내용이요38'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (39, ''제목이요39'', ''내용이요39'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (40, ''제목이요40'', ''내용이요40'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (41, ''제목이요41'', ''내용이요41'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (42, ''제목이요42'', ''내용이요42'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (43, ''제목이요43'', ''내용이요43'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (44, ''제목이요44'', ''내용이요44'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (45, ''제목이요45'', ''내용이요45'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (46, ''제목이요46'', ''내용이요46'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (47, ''제목이요47'', ''내용이요47'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (48, ''제목이요48'', ''내용이요48'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (49, ''제목이요49'', ''내용이요49'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (50, ''제목이요50'', ''내용이요50'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (51, ''제목이요51'', ''내용이요51'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (52, ''제목이요52'', ''내용이요52'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (53, ''제목이요53'', ''내용이요53'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (54, ''제목이요54'', ''내용이요54'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (55, ''제목이요55'', ''내용이요55'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (56, ''제목이요56'', ''내용이요56'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (57, ''제목이요57'', ''내용이요57'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (58, ''제목이요58'', ''내용이요58'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (59, ''제목이요59'', ''내용이요59'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (60, ''제목이요60'', ''내용이요60'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (61, ''제목이요61'', ''내용이요61'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (62, ''제목이요62'', ''내용이요62'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (63, ''제목이요63'', ''내용이요63'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (64, ''제목이요64'', ''내용이요64'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (65, ''제목이요65'', ''내용이요65'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (66, ''제목이요66'', ''내용이요66'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (67, ''제목이요67'', ''내용이요67'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (68, ''제목이요68'', ''내용이요68'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (69, ''제목이요69'', ''내용이요69'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (70, ''제목이요70'', ''내용이요70'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (71, ''제목이요71'', ''내용이요71'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (72, ''제목이요72'', ''내용이요72'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (73, ''제목이요73'', ''내용이요73'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (74, ''제목이요74'', ''내용이요74'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (75, ''제목이요75'', ''내용이요75'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (76, ''제목이요76'', ''내용이요76'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (77, ''제목이요77'', ''내용이요77'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (78, ''제목이요78'', ''내용이요78'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (79, ''제목이요79'', ''내용이요79'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (80, ''제목이요80'', ''내용이요80'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (81, ''제목이요81'', ''내용이요81'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (82, ''제목이요82'', ''내용이요82'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (83, ''제목이요83'', ''내용이요83'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (84, ''제목이요84'', ''내용이요84'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (85, ''제목이요85'', ''내용이요85'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (86, ''제목이요86'', ''내용이요86'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (87, ''제목이요87'', ''내용이요87'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (88, ''제목이요88'', ''내용이요88'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (89, ''제목이요89'', ''내용이요89'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (90, ''제목이요90'', ''내용이요90'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (91, ''제목이요91'', ''내용이요91'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (92, ''제목이요92'', ''내용이요92'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (93, ''제목이요93'', ''내용이요93'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (94, ''제목이요94'', ''내용이요94'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (95, ''제목이요95'', ''내용이요95'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (96, ''제목이요96'', ''내용이요96'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (97, ''제목이요97'', ''내용이요97'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (98, ''제목이요98'', ''내용이요98'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (99, ''제목이요99'', ''내용이요99'', NULL, SYSDATE(), SYSDATE());
INSERT INTO PORTAL_DB.BOARD (ID, TITLE, CONTENT, USER_ID, REG_DATE, UPT_DATE)
VALUES (100, ''제목이요100'', ''내용이요100'', NULL, SYSDATE(), SYSDATE());
COMMIT;